apiVersion: v1
kind: Service
metadata:
  name: k8-sumaapp-service
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 4000
  type: NodePort
  #type: LoadBalancer
  selector:
    app: k8-sumaapp-pod
